services:
  fe-app:
    build:
      context: ..
      dockerfile: ./deployment/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ..:/app
    command: "npm run start"
    extra_hosts:
      - "host.docker.internal:host-gateway"
